# Generated by Django 3.0.6 on 2020-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='path',
            field=models.CharField(max_length=999),
        ),
    ]
